[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
secure_voting = "H194n25SeQTsUFnXWeySFND4Hi3xB5aktuSaKWKSgbFR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/max/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
