[workspace]
members = [
    "programs/secure_voting"
]
resolver = "2"

[profile.release]
overflow-checks = false
lto = "fat"
codegen-units = 1
opt-level = "z"
panic = "abort"
[profile.release.build-override]
opt-level = "z"
incremental = false
codegen-units = 1

